name: Node.js CI and Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment (version 16)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-node-app .

      # Step 5: SSH into EC2 and deploy the Docker container
      - name: Deploy to EC2 (via SSH)
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}  # EC2 public IP
          username: ec2-user                  # EC2 username (usually ec2-user or ubuntu)
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # Private key for SSH
          script: |
            # Install Docker (if not installed)
            if ! command -v docker &> /dev/null
            then
                echo "Docker could not be found, installing Docker..."
                curl https://get.docker.com
            fi

            # Pull the latest image (if the image is built on the EC2 instance)
            docker pull my-node-app:latest || true

            # Run the container (stop any previous container if running)
            docker ps -q --filter "name=my-node-app" | grep -q . && docker stop my-node-app && docker rm my-node-app || true

            # Run the new Docker container
            docker run -d --name my-node-app -p 8080:8080 my-node-app:latest
