name: Expression Example Workflow

on:
  workflow_dispatch:
    inputs:
      deployment_env:
        description: "Specify the deployment environment (development or production)"
        required: true
        default: "development"

jobs:
  conditional-steps:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check the Deployment Environment from Input
      - name: Dynamic Environment Selection
        run: |
          if [ "${{ inputs.deployment_env }}" == "production" ]; then
            echo "Deploying to the Production Environment"
          elif [ "${{ inputs.deployment_env }}" == "development" ]; then
            echo "Deploying to the Development Environment"
          else
            echo "Unknown deployment environment: ${{ inputs.deployment_env }}"
            exit 1
          fi

      # Step 2: Show Workflow Actor and Environment
      - name: Show Actor and Selected Environment
        run: |
          echo "Workflow triggered by: ${{ github.actor }}"
          echo "Selected Environment: ${{ inputs.deployment_env }}"
