name: First Workflow

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: echo "This is the first step"

      - name: Multiple Commands
        run: |
          node -v
          npm -v
  
  #parallel jobs
  parallel-jobs:
    runs-on: macos:latest
    steps:
      - name: View SW Version
        run: sw_vers 

  #Dependent Jobs
  Dependent-Jobs:
    runs-on: windows:latest
    needs: run-shell-commands
    steps:
      - name: echo a string
        run: Write-Output "Windows String"
      - name: Error Step
        run: doesnotexist